# Week 1 Day 2 Checkpoint — NumPy from Scratch

**Goal:** Test understanding of NumPy basics without looking at any previous code.

---

## What I built:

### Task 1 — Array Operations
Created a (5,4) NumPy array of random floats and computed:
- Mean of each column using axis=0
- Max of each row using axis=1
- Standard deviation of the whole array

**Key learning:** axis=0 collapses rows → one result per column.
axis=1 collapses columns → one result per row.

---

### Task 2 — Boolean Indexing
Created an array of 50 random integers (0–100) and:
- Extracted all values above 60 using arr[arr > 60]
- Counted them using .size
- Replaced all values below 40 with 0

**Key learning:** Boolean indexing lets you filter and modify
array values in one line — no loops needed.

---

### Task 3 — Confusion Matrix from Scratch
Given y_true and y_pred arrays, calculated:
- TP, TN, FP, FN using a loop with conditions
- Precision = TP / (TP + FP)
- Recall = TP / (TP + FN)

**Key learning:** Precision tells you how many of your
positive predictions were actually correct.
Recall tells you how many actual positives you caught.

In [1]:
import numpy as np

data = np.random.rand(5, 4)

print("Array:\n", data)
print("\nMean of each column (axis=0):", data.mean(axis=0))
print("Max of each row (axis=1):", data.max(axis=1))
print("Std of whole array:", data.std())

Array:
 [[0.1441357  0.63912694 0.72850018 0.41478498]
 [0.3261085  0.57871068 0.37357455 0.84100757]
 [0.29842365 0.46884518 0.10347618 0.05394017]
 [0.6104592  0.62111746 0.02163461 0.84858888]
 [0.89403197 0.31160041 0.9500764  0.97237458]]

Mean of each column (axis=0): [0.4546318  0.52388013 0.43545238 0.62613924]
Max of each row (axis=1): [0.72850018 0.84100757 0.46884518 0.84858888 0.97237458]
Std of whole array: 0.2969551348674606


In [2]:
import numpy as np

arr = np.random.randint(0, 100, 50)
print("Original array:", arr)

above_60 = arr[arr > 60]
print("\nValues above 60:", above_60)

count = above_60.size
print("Count above 60:", count)

arr[arr < 40] = 0
print("\nArray after replacing below 40 with 0:", arr)

Original array: [ 4 42 78 69 89 87 22 65 59 15 48 26 24 31  5 30 26  9 68 59 46 56 85 80
 83 81 72 29 97 77 82  6 54 40 91 15 18 27  4 19 76 75  3 51  4 81 72 44
 16 94]

Values above 60: [78 69 89 87 65 68 85 80 83 81 72 97 77 82 91 76 75 81 72 94]
Count above 60: 20

Array after replacing below 40 with 0: [ 0 42 78 69 89 87  0 65 59  0 48  0  0  0  0  0  0  0 68 59 46 56 85 80
 83 81 72  0 97 77 82  0 54 40 91  0  0  0  0  0 76 75  0 51  0 81 72 44
  0 94]


In [4]:
import numpy as np
y_true = np.array([1, 0, 1, 1, 0, 1, 0, 0, 1, 0])
y_pred = np.array([1, 0, 1, 0, 0, 1, 1, 0, 1, 1])

TP = np.sum((y_pred == 1) & (y_true == 1))
TN = np.sum((y_pred == 0) & (y_true == 0))
FP = np.sum((y_pred == 1) & (y_true == 0))
FN = np.sum((y_pred == 0) & (y_true == 1))

Precision = TP / (TP + FP)
Recall    = TP / (TP + FN)

print("=" * 30)
print("    CONFUSION MATRIX RESULTS")
print("=" * 30)
print(f"  True Positive  (TP) : {TP}")
print(f"  True Negative  (TN) : {TN}")
print(f"  False Positive (FP) : {FP}")
print(f"  False Negative (FN) : {FN}")
print("-" * 30)
print(f"  Precision           : {Precision:.2f}")
print(f"  Recall              : {Recall:.2f}")
print("=" * 30)

    CONFUSION MATRIX RESULTS
  True Positive  (TP) : 4
  True Negative  (TN) : 3
  False Positive (FP) : 2
  False Negative (FN) : 1
------------------------------
  Precision           : 0.67
  Recall              : 0.80


In [5]:
# Simpler Version
y_true = [1, 0, 1, 1, 0, 1, 0, 0, 1, 0]
y_pred = [1, 0, 1, 0, 0, 1, 1, 0, 1, 1]

TP = 0
TN = 0
FP = 0
FN = 0

for i in range(10):
    if y_pred[i] == 1 and y_true[i] == 1:
        TP += 1
    elif y_pred[i] == 0 and y_true[i] == 0:
        TN += 1
    elif y_pred[i] == 0 and y_true[i] == 1:
        FN += 1
    else:
        FP += 1

Precision = TP / (TP + FP)
Recall    = TP / (TP + FN)

print("=" * 30)
print("    CONFUSION MATRIX RESULTS")
print("=" * 30)
print(f"  True Positive  (TP) : {TP}")
print(f"  True Negative  (TN) : {TN}")
print(f"  False Positive (FP) : {FP}")
print(f"  False Negative (FN) : {FN}")
print("-" * 30)
print(f"  Precision           : {Precision:.2f}")
print(f"  Recall              : {Recall:.2f}")
print("=" * 30)

    CONFUSION MATRIX RESULTS
  True Positive  (TP) : 4
  True Negative  (TN) : 3
  False Positive (FP) : 2
  False Negative (FN) : 1
------------------------------
  Precision           : 0.67
  Recall              : 0.80
